services:
  diwe-challenge-db:
    environment:
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db:/var/lib/mysql

  diwe-challenge-api:
    ports:
    - $PORT:$PORT
    - $DEBUGGER_PORT:$DEBUGGER_PORT
    command: npm run dev

volumes:
  db: