services:
  diwe-challenge-db:
    container_name: diwe-challenge-db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    ports:
      - $DB_PORT:3306
    command: --default-authentication-plugin=mysql_native_password

  diwe-challenge-api:
    depends_on:
      - diwe-challenge-db
    container_name: diwe-challenge-api
    image: renatosbispo/diwe-challenge-api
    build:
      context: .
      target: base
    volumes:
      - ./src:/app/src
    network_mode: host
    command: npm run test