services:

  diwe-challenge-db-dev:
    container_name: diwe-challenge-db-dev
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=$DEV_DB_ROOT_PASSWORD
      - MYSQL_TCP_PORT=$DEV_DB_PORT
    ports:
      - $DEV_DB_PORT:$DEV_DB_PORT
    volumes:
    - db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  diwe-challenge-db-test:
    container_name: diwe-challenge-db-test
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=$TEST_DB_ROOT_PASSWORD
      - MYSQL_TCP_PORT=$TEST_DB_PORT
    ports:
      - $TEST_DB_PORT:$TEST_DB_PORT
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db: